### ISSUE TITLE
error: pkg_resources.DistributionNotFound: greenlet>=0.3

### ISSUE THREAD

**Issue by laflour** [progrium/localtunnel#118]
Hello,

get another error on windows laptop when running localtunnel-beta

C:\Python27\Scripts>localtunnel-beta.exe 63121
Traceback (most recent call last):
  File "C:\Python27\Scripts\localtunnel-beta-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build\bdist.win32\egg\pkg_resources.py", line 2793, in <module>
  File "build\bdist.win32\egg\pkg_resources.py", line 673, in require
  File "build\bdist.win32\egg\pkg_resources.py", line 576, in resolve
pkg_resources.DistributionNotFound: greenlet>=0.3

**Comment by progrium** [comment]
That version has reached EOL anyway
