### ISSUE TITLE
is localtunnel down?

### ISSUE THREAD

**Issue by ImBobby** [progrium/localtunnel#125]
I tried running `lt --port 80` and it returns

``` bash
Error: localtunnel server returned an error, please try again
    at Request._callback (/usr/local/lib/node_modules/localtunnel/client.js:205:27)
    at Request.self.callback (/usr/local/lib/node_modules/localtunnel/node_modules/request/main.js:122:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/main.js:655:16)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/localtunnel/node_modules/request/main.js:617:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
```

**Comment by progrium** [comment]
Cool. Well you're using some knockoff version of localtunnel because I've never written a version in Node.js

**Comment by ImBobby** [comment]
I am so so sorry I feel like an idiot. I opened an issue in the wrong repo. it should be here github.com/defunctzombie/localtunnel. Really sorry, won't bother you anymore.
