### ISSUE TITLE
discover_backend_port fails with localtunnel-beta

### ISSUE THREAD

**Issue by kevinburke** [progrium/localtunnel#78]
I am not sure of the cause but hoped you would be able to see from the stack trace.

```
Traceback (most recent call last):
  File "/usr/local/share/python/localtunnel-beta", line 9, in <module>
    load_entry_point('localtunnel==0.5.8', 'console_scripts', 'localtunnel-beta')()
  File "/usr/local/lib/python2.7/site-packages/localtunnel/client/client.py", line 73, in run
    backend_port = util.discover_backend_port(host[0])
  File "/usr/local/lib/python2.7/site-packages/localtunnel/util.py", line 45, in discover_backend_port
    headers={"Host": "_backend.{0}".format(hostname)}))
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1207, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

Steps to reproduce:

`pip install localtunnel` on a Snow Leopard with Python 2.7.

**Comment by progrium** [comment]
Both versions have reached EOL today.
