### ISSUE TITLE
urllib error

### ISSUE THREAD

**Issue by samdraz** [progrium/localtunnel#87]
*i got the following issue*
```
Traceback (most recent call last):
  File "/usr/local/bin/localtunnel-beta", line 9, in <module>
    load_entry_point('localtunnel==0.5.8', 'console_scripts', 'localtunnel-beta')()
  File "/usr/local/lib/python2.7/dist-packages/localtunnel/client/client.py", line 73, in run
    backend_port = util.discover_backend_port(host[0])
  File "/usr/local/lib/python2.7/dist-packages/localtunnel/util.py", line 45, in discover_backend_port
    headers={"Host": "_backend.{0}".format(hostname)}))
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 401, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 419, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1211, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

```

**Comment by progrium** [comment]
That version has reached EOL.
